import React, { useState } from "react";
import {
  Sparkles,
  Copy,
  Check,
  Download,
  Palette,
  RefreshCw,
  AlertCircle,
  Eye,
  Sliders,
  Share2,
} from "lucide-react";
import { GeneratedLogo, SuggestedBrandPalette } from "../types";

interface BrandPaletteStudioProps {
  companyName: string;
  industry: string;
  description: string;
  currentLogo: GeneratedLogo | null;
  onApplyPalette?: (paletteName: string, colors: string[]) => void;
  isOpen?: boolean;
  onClose?: () => void;
}

export const BrandPaletteStudio: React.FC<BrandPaletteStudioProps> = ({
  companyName,
  industry,
  description,
  currentLogo,
  onApplyPalette,
  isOpen = true,
  onClose,
}) => {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [palette, setPalette] = useState<SuggestedBrandPalette | null>(null);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [exportSuccess, setExportSuccess] = useState<string | null>(null);

  const handleCopy = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleAnalyzePalette = async () => {
    setIsAnalyzing(true);
    setError(null);

    try {
      const res = await fetch("/api/suggest-palette", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          companyName: companyName || currentLogo?.companyName || "Innovate",
          industry: industry || currentLogo?.industry || "Technology & AI",
          description: description || currentLogo?.promptUsed || "High-end corporate identity",
          logoBase64: currentLogo?.imageUrl || null,
        }),
      });

      const data = await res.json();
      if (res.ok && data.primary) {
        setPalette(data);
      } else {
        throw new Error(data.error || "Failed to analyze palette");
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to connect to palette analysis engine");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleExportCSS = () => {
    if (!palette) return;
    const css = `:root {
  /* ${palette.paletteName} - Generated by BrandForge Studio */
  --brand-primary: ${palette.primary.hex};
  --brand-secondary: ${palette.secondary.hex};
  --brand-accent: ${palette.accent.hex};
  --brand-bg: ${palette.background.hex};
  --brand-surface: ${palette.surface.hex};
  --brand-text: ${palette.text.hex};
}`;
    navigator.clipboard.writeText(css);
    setExportSuccess("Copied CSS Variables to Clipboard");
    setTimeout(() => setExportSuccess(null), 3000);
  };

  const handleExportJSON = () => {
    if (!palette) return;
    const blob = new Blob([JSON.stringify(palette, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${companyName || "brand"}-color-palette.json`;
    a.click();
    URL.revokeObjectURL(url);
    setExportSuccess("Downloaded palette JSON file");
    setTimeout(() => setExportSuccess(null), 3000);
  };

  if (!isOpen) return null;

  return (
    <div className="bg-[#151515] border border-[#333] p-6 sm:p-8 relative">
      {/* Bauhaus Corner Accent */}
      <div className="absolute -top-px -left-px w-3 h-3 border-t-2 border-l-2 border-[#FF3B00] pointer-events-none"></div>

      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-[#222]">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-[#FF3B00] font-black">
              CHROMATIC INTELLIGENCE // AI PALETTE
            </span>
            <span className="text-[9px] font-mono uppercase tracking-widest px-2 py-0.5 border border-[#333] text-white/50 bg-[#0E0E0E]">
              WCAG AA/AAA
            </span>
          </div>
          <h3 className="text-base sm:text-lg font-black uppercase tracking-tight text-white mt-1">
            Complementary Brand Color System
          </h3>
          <p className="text-[11px] font-mono text-white/50 mt-0.5">
            Analyzes company archetype & emblem geometry to synthesize primary, secondary, and accent harmonies.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            id="btn-analyze-palette"
            disabled={isAnalyzing}
            onClick={handleAnalyzePalette}
            className="px-4 py-2.5 bg-[#FF3B00] text-black font-black uppercase text-[10px] tracking-widest hover:bg-white transition-colors cursor-pointer flex items-center gap-2 disabled:opacity-50"
          >
            <Sparkles className={`w-3.5 h-3.5 ${isAnalyzing ? "animate-spin" : ""}`} />
            <span>{isAnalyzing ? "Analyzing Colors..." : palette ? "Re-Analyze" : "Analyze Brand Palette"}</span>
          </button>

          {onClose && (
            <button
              onClick={onClose}
              className="p-2 border border-[#333] text-white/60 hover:text-white text-xs font-mono"
            >
              ✕
            </button>
          )}
        </div>
      </div>

      {error && (
        <div className="mt-4 p-3.5 bg-red-950/40 border border-red-800/60 text-red-300 text-xs font-mono flex items-center gap-2">
          <AlertCircle className="w-4 h-4 flex-shrink-0 text-red-400" />
          <span>{error}</span>
        </div>
      )}

      {exportSuccess && (
        <div className="mt-4 p-2.5 bg-emerald-950/50 border border-emerald-500/50 text-emerald-300 text-xs font-mono flex items-center gap-2">
          <Check className="w-3.5 h-3.5 text-emerald-400" />
          <span>{exportSuccess}</span>
        </div>
      )}

      {/* Initial Empty State */}
      {!palette && !isAnalyzing && (
        <div className="text-center py-10 px-4 border border-[#222] bg-[#0E0E0E] mt-6">
          <div className="w-12 h-12 rounded-full border border-[#333] bg-[#151515] flex items-center justify-center mx-auto mb-3">
            <Palette className="w-5 h-5 text-[#FF3B00]" />
          </div>
          <h4 className="text-xs font-black uppercase tracking-widest text-white">
            No Active Palette Computed
          </h4>
          <p className="text-[10px] font-mono text-white/40 mt-1 max-w-md mx-auto">
            Click &ldquo;Analyze Brand Palette&rdquo; to have Gemini inspect your company description
            {currentLogo ? " and current logo mark" : ""} to determine optical color harmonics.
          </p>
          <div className="mt-4 flex items-center justify-center gap-3">
            <span className="text-[9px] font-mono text-white/30 uppercase">Required outputs:</span>
            <span className="text-[9px] font-mono text-[#FF3B00]">Primary</span>
            <span className="text-white/20">•</span>
            <span className="text-[9px] font-mono text-sky-400">Secondary</span>
            <span className="text-white/20">•</span>
            <span className="text-[9px] font-mono text-amber-400">Accent</span>
          </div>
        </div>
      )}

      {/* Loading state */}
      {isAnalyzing && (
        <div className="text-center py-12 px-4 border border-[#222] bg-[#0E0E0E] mt-6">
          <div className="relative w-12 h-12 mx-auto mb-3">
            <div className="absolute inset-0 rounded-full border-2 border-[#FF3B00]/20 border-t-[#FF3B00] animate-spin"></div>
            <Palette className="w-5 h-5 text-[#FF3B00] absolute inset-3.5 animate-pulse" />
          </div>
          <p className="text-xs font-black uppercase tracking-widest text-white">
            Computing Optical Chromatic Ratios
          </p>
          <p className="text-[10px] font-mono text-[#FF3B00] mt-1">
            Analyzing contrast ratios, color wheel harmonies, and sector psychology...
          </p>
        </div>
      )}

      {/* Computed Palette System */}
      {palette && !isAnalyzing && (
        <div className="mt-6 space-y-6">
          {/* Summary Banner */}
          <div className="p-4 bg-[#0E0E0E] border border-[#222] flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2">
                <span className="text-xs font-black uppercase tracking-wider text-white">
                  {palette.paletteName}
                </span>
                <span className="text-[9px] font-mono uppercase tracking-widest px-2 py-0.5 bg-[#FF3B00]/10 text-[#FF3B00] border border-[#FF3B00]/30">
                  {palette.harmonyType}
                </span>
              </div>
              <p className="text-[11px] font-light text-white/70 mt-1 max-w-2xl leading-relaxed">
                {palette.rationale}
              </p>
              {palette.typographySuggestion && (
                <div className="mt-2 text-[10px] font-mono text-white/40">
                  Typography Recommendation: <span className="text-white/70">{palette.typographySuggestion}</span>
                </div>
              )}
            </div>

            {/* Quick Export Actions */}
            <div className="flex items-center gap-2 flex-shrink-0">
              <button
                type="button"
                onClick={handleExportCSS}
                className="px-3 py-2 border border-[#333] hover:border-white bg-[#151515] text-white/80 hover:text-white text-[9px] font-mono uppercase tracking-widest flex items-center gap-1.5 cursor-pointer"
                title="Copy CSS variables"
              >
                <Copy className="w-3 h-3 text-[#FF3B00]" />
                <span>CSS Vars</span>
              </button>

              <button
                type="button"
                onClick={handleExportJSON}
                className="px-3 py-2 border border-[#333] hover:border-white bg-[#151515] text-white/80 hover:text-white text-[9px] font-mono uppercase tracking-widest flex items-center gap-1.5 cursor-pointer"
                title="Download JSON file"
              >
                <Download className="w-3 h-3 text-[#FF3B00]" />
                <span>JSON</span>
              </button>

              {onApplyPalette && (
                <button
                  type="button"
                  onClick={() =>
                    onApplyPalette(palette.paletteName, [
                      palette.primary.hex,
                      palette.secondary.hex,
                      palette.accent.hex,
                    ])
                  }
                  className="px-3 py-2 bg-white text-black font-black uppercase text-[9px] tracking-widest hover:bg-[#FF3B00] hover:text-white transition-colors cursor-pointer"
                >
                  Apply to Studio
                </button>
              )}
            </div>
          </div>

          {/* Primary Swatches Grid (Primary, Secondary, Accent) */}
          <div>
            <label className="text-[10px] uppercase tracking-[0.2em] text-[#FF3B00] font-black mb-3 block">
              Core Brand Triad
            </label>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {/* Primary Color Card */}
              <div className="border border-[#333] bg-[#0E0E0E] overflow-hidden group">
                <div
                  className="h-24 relative flex items-end p-3 transition-transform group-hover:scale-[1.01]"
                  style={{ backgroundColor: palette.primary.hex }}
                >
                  <span className="text-[10px] font-mono uppercase font-black px-2 py-0.5 bg-black/70 text-white backdrop-blur-sm">
                    {palette.primary.hex}
                  </span>
                </div>
                <div className="p-4 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-[9px] font-mono uppercase tracking-widest text-[#FF3B00] font-black">
                      PRIMARY COLOR
                    </span>
                    <button
                      onClick={() => handleCopy(palette.primary.hex, "primary")}
                      className="p-1 hover:text-white text-white/40 text-xs transition-colors cursor-pointer"
                      title="Copy HEX"
                    >
                      {copiedKey === "primary" ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                    </button>
                  </div>
                  <h4 className="text-xs font-bold text-white uppercase">{palette.primary.name}</h4>
                  <p className="text-[10px] font-light text-white/60 leading-tight">
                    {palette.primary.usage}
                  </p>
                  {palette.primary.contrast && (
                    <div className="text-[9px] font-mono text-white/40 pt-1 border-t border-[#222]">
                      Contrast: <span className="text-emerald-400 font-bold">{palette.primary.contrast}</span>
                    </div>
                  )}
                </div>
              </div>

              {/* Secondary Color Card */}
              <div className="border border-[#333] bg-[#0E0E0E] overflow-hidden group">
                <div
                  className="h-24 relative flex items-end p-3 transition-transform group-hover:scale-[1.01]"
                  style={{ backgroundColor: palette.secondary.hex }}
                >
                  <span className="text-[10px] font-mono uppercase font-black px-2 py-0.5 bg-black/70 text-white backdrop-blur-sm">
                    {palette.secondary.hex}
                  </span>
                </div>
                <div className="p-4 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-[9px] font-mono uppercase tracking-widest text-sky-400 font-black">
                      SECONDARY COLOR
                    </span>
                    <button
                      onClick={() => handleCopy(palette.secondary.hex, "secondary")}
                      className="p-1 hover:text-white text-white/40 text-xs transition-colors cursor-pointer"
                      title="Copy HEX"
                    >
                      {copiedKey === "secondary" ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                    </button>
                  </div>
                  <h4 className="text-xs font-bold text-white uppercase">{palette.secondary.name}</h4>
                  <p className="text-[10px] font-light text-white/60 leading-tight">
                    {palette.secondary.usage}
                  </p>
                  {palette.secondary.contrast && (
                    <div className="text-[9px] font-mono text-white/40 pt-1 border-t border-[#222]">
                      Contrast: <span className="text-sky-400 font-bold">{palette.secondary.contrast}</span>
                    </div>
                  )}
                </div>
              </div>

              {/* Accent Color Card */}
              <div className="border border-[#333] bg-[#0E0E0E] overflow-hidden group">
                <div
                  className="h-24 relative flex items-end p-3 transition-transform group-hover:scale-[1.01]"
                  style={{ backgroundColor: palette.accent.hex }}
                >
                  <span className="text-[10px] font-mono uppercase font-black px-2 py-0.5 bg-black/70 text-white backdrop-blur-sm">
                    {palette.accent.hex}
                  </span>
                </div>
                <div className="p-4 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-[9px] font-mono uppercase tracking-widest text-amber-400 font-black">
                      ACCENT HIGHLIGHT
                    </span>
                    <button
                      onClick={() => handleCopy(palette.accent.hex, "accent")}
                      className="p-1 hover:text-white text-white/40 text-xs transition-colors cursor-pointer"
                      title="Copy HEX"
                    >
                      {copiedKey === "accent" ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                    </button>
                  </div>
                  <h4 className="text-xs font-bold text-white uppercase">{palette.accent.name}</h4>
                  <p className="text-[10px] font-light text-white/60 leading-tight">
                    {palette.accent.usage}
                  </p>
                  {palette.accent.contrast && (
                    <div className="text-[9px] font-mono text-white/40 pt-1 border-t border-[#222]">
                      Contrast: <span className="text-amber-400 font-bold">{palette.accent.contrast}</span>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Supporting Canvas & Typography Neutrals */}
          <div>
            <label className="text-[10px] uppercase tracking-[0.2em] text-[#FF3B00] font-black mb-3 block">
              Architectural Neutrals & Typography
            </label>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {[
                { label: "Background", color: palette.background, key: "bg" },
                { label: "Surface / Card", color: palette.surface, key: "surface" },
                { label: "High-Contrast Text", color: palette.text, key: "text" },
              ].map((item) => (
                <div
                  key={item.key}
                  className="p-3 border border-[#333] bg-[#0E0E0E] flex items-center justify-between"
                >
                  <div className="flex items-center gap-3">
                    <div
                      className="w-7 h-7 border border-[#444] flex-shrink-0"
                      style={{ backgroundColor: item.color.hex }}
                    />
                    <div>
                      <div className="text-[9px] font-mono uppercase tracking-widest text-white/50">
                        {item.label}
                      </div>
                      <div className="text-[11px] font-bold text-white font-mono uppercase">
                        {item.color.hex}
                      </div>
                    </div>
                  </div>
                  <button
                    onClick={() => handleCopy(item.color.hex, item.key)}
                    className="p-1 hover:text-white text-white/40 text-xs transition-colors cursor-pointer"
                    title="Copy HEX"
                  >
                    {copiedKey === item.key ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* Live Mockup Identity Card: Preview how the brand looks with these colors */}
          <div className="p-6 border border-[#333] relative overflow-hidden" style={{ backgroundColor: palette.background.hex }}>
            <div className="absolute top-2 right-3 text-[9px] font-mono uppercase tracking-widest opacity-40" style={{ color: palette.text.hex }}>
              COMPUTED HARMONY PREVIEW
            </div>
            <div className="flex flex-col sm:flex-row items-center gap-6">
              {currentLogo ? (
                <div
                  className="w-24 h-24 p-3 border flex items-center justify-center flex-shrink-0"
                  style={{
                    backgroundColor: palette.surface.hex,
                    borderColor: palette.primary.hex + "40",
                  }}
                >
                  <img
                    src={currentLogo.imageUrl}
                    alt={companyName}
                    referrerPolicy="no-referrer"
                    className="max-w-full max-h-full object-contain"
                  />
                </div>
              ) : (
                <div
                  className="w-24 h-24 border flex items-center justify-center flex-shrink-0 font-black text-2xl"
                  style={{
                    backgroundColor: palette.surface.hex,
                    borderColor: palette.primary.hex,
                    color: palette.primary.hex,
                  }}
                >
                  {(companyName || "M").charAt(0).toUpperCase()}
                </div>
              )}

              <div className="space-y-2 text-center sm:text-left flex-1">
                <div
                  className="inline-block px-2.5 py-0.5 text-[9px] font-mono uppercase tracking-widest font-black"
                  style={{
                    backgroundColor: palette.accent.hex,
                    color: palette.background.hex,
                  }}
                >
                  {industry || "Corporate Identity"}
                </div>
                <h3
                  className="text-xl sm:text-2xl font-black tracking-tight"
                  style={{ color: palette.text.hex }}
                >
                  {companyName || "BrandForge Labs"}
                </h3>
                <p
                  className="text-xs font-light max-w-lg leading-relaxed opacity-80"
                  style={{ color: palette.text.hex }}
                >
                  Demonstrating brand authority through balanced optical hierarchy: primary mark with secondary structure and energetic accent feedback.
                </p>
                <div className="flex items-center gap-3 pt-2 justify-center sm:justify-start">
                  <button
                    style={{
                      backgroundColor: palette.primary.hex,
                      color: palette.background.hex,
                    }}
                    className="px-4 py-2 text-[10px] font-black uppercase tracking-widest cursor-pointer shadow-md"
                  >
                    Primary Button
                  </button>
                  <button
                    style={{
                      borderColor: palette.secondary.hex,
                      color: palette.text.hex,
                      backgroundColor: palette.surface.hex,
                    }}
                    className="px-4 py-2 border text-[10px] font-bold uppercase tracking-widest cursor-pointer"
                  >
                    Secondary Action
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
